### PR TITLE
Handle UnivCo

### PR DESCRIPTION
**Pull request by conal**
Handle `UnivCo`: navigation, transformation, pretty-printing. I was in some unfamiliar territory, and I don't have any tests. Some questions:

* `ppCoercion` in `HERMIT.PrettyPrinter.AST`: should there be a catch-all here as in `ppCoercionR` from `HERMIT.PrettyPrinter.Clean`?
* I'm skipping `UnivCo` in `allR` in the `Walker c Coercion` instance in `HERMIT.Kure`. Is that what we want? I guess so, as with `Refl`.
* In `HERMIT.PrettyPrinter.Clean.ppCoercion`, for the `UnivCo` case, should I use `retApps`?

### CODE REVIEW

**Comment by conal** [comment]
I see the "Merge remote-tracking branch 'upstream/master'" commit listed here (presumably for @xich's merge of my previous pull request) in addition to my new content. Am I doing something wonky with git?

**Comment by conal** [comment]
See conversation at #160.

**Comment by xich** [comment]
I think, instead of a catch-all case, we should use readerT (http://hackage.haskell.org/package/kure-2.16.12/docs/Language-KURE-Combinators-Transform.html) so we get an exhaustiveness check from GHC... but we can do that in another diff.

Yes, no need for UnivCo in the `Walker c Coercion` instance because a `UnivCo` doesn't contain other coercions.

Yes, I would use `retApps` so the types get parens around them if necessary.

I think the merge commit would disappear if you rebased this onto my merge commit for SubCo, but that would probably require a `git push -f`... we can just see what happens to it when I merge this in. Mind doing the `retApps` bit? Otherwise looks good!

**Comment by conal** [comment]
@xich Thanks. I added a commit with `retApps`.

Makes sense about `UnivCo` having no sub-conversions.

I need to learn git better.

**Comment by xich** [comment]
Eh, git I understand... github, on the other hand, is still a mystery much of the time.

Thanks for the patches!

**Pull request merged**
